DECLARE @db_name sysname = N'$(MSSQL_DATABASE)';

IF DB_ID(@db_name) IS NULL
BEGIN
    DECLARE @sql NVARCHAR(MAX);
    SET @sql = N'CREATE DATABASE [' + REPLACE(@db_name, N']', N']]') + N']';
    EXEC(@sql);
END;
GO

USE [@db_name]

IF EXISTS (SELECT * FROM USERS)
BEGIN
  INSERT INTO USERS VALUES (1, 1, 1, 1, 'ADMIN', '0436c5121be46840cd1229e04741e828966027dba34a0ee1592f35b1a4c6664ed07d00dfb5dd239d', 'ADMIN')
END
IF EXISTS (SELECT * FROM PERMISSION)
BEGIN
  INSERT INTO PERMISSION VALUES ('ADMIN')
  INSERT INTO PERMISSION VALUES ('MANAGER')
  INSERT INTO PERMISSION VALUES ('COMMON_USER')
END
IF EXISTS (SELECT * FROM user_permission)
BEGIN
  INSERT INTO user_permission VALUES (1, 1)
END
