spring:
  datasource:
    url: "jdbc:sqlserver://CATELAN\\SQLEXPRESS;databaseName=BANCO_CONSULTA;sendStringParametersAsUnicode=false;encrypt=false;"
    username: 'sa'
    password: '28phfktlan02'
    driver=class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect